version: '3.7'

services:
  proxy:
    image: kong:latest
    restart: always
    network_mode: host
    user: root
    container_name: proxy
    environment:
      - KONG_DATABASE=off
      - KONG_NGINX_MAIN_WORKER_RLIMIT_NOFILE=100000
      - KONG_NGINX_EVENTS_WORKER_CONNECTIONS=100000
      - KONG_NGINX_EVENTS_USE=epoll
      - KONG_NGINX_HTTP_OPEN_FILE_CACHE=max=200000 inactive=20s
      - KONG_NGINX_HTTP_OPEN_FILE_CACHE_VALID=30s
      - KONG_NGINX_HTTP_OPEN_FILE_CACHE_MIN_USES=2
      - KONG_NGINX_HTTP_OPEN_FILE_CACHE_ERRORS=on
      - KONG_NGINX_HTTP_TCP_NODELAY=on
      - KONG_NGINX_HTTP_KEEPALIVE_REQUESTS=100000
      - KONG_NGINX_HTTP_KEEPALIVE_TIMEOUT=300
      - KONG_ANONYMOUS_REPORTS=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/conf.d/kong.yml
      - KONG_ADMIN_LISTEN=127.0.0.1:9001
      - KONG_PROXY_LISTEN=0.0.0.0:80 reuseport backlog=65535, 0.0.0.0:443 ssl http2 reuseport backlog=65535
      - KONG_TRUSTED_IPS=0.0.0.0/0,::/0
      - KONG_REAL_IP_RECURSIVE=on
      - KONG_STATUS_LISTEN=127.0.0.1:9123
      - KONG_PROXY_ACCESS_LOG=/dev/null
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_HEADERS=off
    volumes:
      - ./conf.d:/etc/kong/conf.d

    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 2 
